apiVersion: v1
kind: Pod
metadata:
  name: fashion-store-pod
  namespace: citi-ns
  labels:
    app: fashion-store
spec:
  containers:
    - name: fashion-store
      image: ip-banksy-repo1-docker-local.artifactory.swg-devops.com/banksy/fashion-store/citi:latest
      ports:
        - name: fashion-store
          protocol: TCP
          containerPort: 8080
      env:
        - name: NODE_ENV
          value: nike
  imagePullSecrets:
    - name: artifactory-docker-registry-secret
      #envFrom:
      #- configMapRef:
      #    name: api-controller-configmap
