apiVersion: v1
kind: Service
metadata:
  name: shoe-store-svc
  namespace: banksy-ns
spec:
  type: NodePort
  ports:
  - name: shoe-store
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32003
  selector:
    app: shoe-store
